/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BackgroundSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'name', 'style', 'updatedAt'] as const
  $columns = BackgroundSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare name: string
  @column()
  declare style: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FocusSessionSchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'id', 'pomoCount', 'stopwatchMs', 'updatedAt', 'userId'] as const
  $columns = FocusSessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pomoCount: number
  @column()
  declare stopwatchMs: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class GoalSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'status', 'updatedAt', 'userId'] as const
  $columns = GoalSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class HabitPeriodSchema extends BaseModel {
  static $columns = ['completed', 'count', 'createdAt', 'end', 'habitId', 'id', 'start', 'updatedAt', 'userId'] as const
  $columns = HabitPeriodSchema.$columns
  @column()
  declare completed: boolean
  @column()
  declare count: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare end: DateTime
  @column()
  declare habitId: number
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare start: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class HabitSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'frequency', 'id', 'name', 'reminders', 'target', 'updatedAt', 'userId'] as const
  $columns = HabitSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare frequency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare reminders: any
  @column()
  declare target: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class JournalSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'date', 'id', 'mood', 'updatedAt', 'userId'] as const
  $columns = JournalSchema.$columns
  @column()
  declare body: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mood: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class ScribbleSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'title', 'updatedAt', 'userId'] as const
  $columns = ScribbleSchema.$columns
  @column()
  declare body: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TaskDaySchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'id', 'status', 'taskId', 'updatedAt', 'userId'] as const
  $columns = TaskDaySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column()
  declare taskId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TaskSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'goalId', 'id', 'name', 'pomoCount', 'priority', 'status', 'stopwatchMs', 'updatedAt', 'userId'] as const
  $columns = TaskSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare goalId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare pomoCount: number
  @column()
  declare priority: string
  @column()
  declare status: string
  @column()
  declare stopwatchMs: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'type', 'updatedAt', 'userId'] as const
  $columns = TokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'backgroundId', 'createdAt', 'email', 'emailVerified', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string | null
  @column()
  declare backgroundId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare emailVerified: boolean
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
