/**
 * Favicons are stored in packages/assets/favicon and is generated by https://realfavicongenerator.net
 *
 * Destination is to the following:
 * - atropos site (public/*)
 * - lachesis site (public/*)
 * - lachesis app (tauri's app icon, which requires converting)
 */

import { execSync } from 'child_process'
import { cpSync, readFileSync } from 'fs'
import { styleText } from 'util'

// Copy over to Atropos site
console.log(styleText('gray', 'Copying favicons... (atropos)'))
cpSync('packages/assets/favicon', 'apps/atropos/public', { recursive: true })
console.log(styleText('green', 'Copied favicons! (atropos)'))

// Copy over to Lachesis site
console.log(styleText('gray', 'Copying favicons... (lachesis)'))
cpSync('packages/assets/favicon', 'apps/lachesis/public', { recursive: true })
console.log(styleText('green', 'Copied favicons! (lachesis)'))

// Generate icons for Lachesis tauri app
console.log(styleText('gray', 'Generating icons... (lachesis/app)')) // Extract color from site.webmaniefest
const THEME_COLOR = JSON.parse(readFileSync('packages/assets/favicon/site.webmanifest')).theme_color
execSync(`pnpm tauri icon ../../packages/assets/favicon/favicon.svg --ios-color '${THEME_COLOR}'`, {
  cwd: 'apps/lachesis',
  stdio: 'pipe',
})
console.log(styleText('green', 'Generated icons! (lachesis/app)'))
