/**
 * Favicons are stored in packages/assets/favicon and is generated by https://realfavicongenerator.net
 *
 * Destination is to the following:
 * - atropos site (public/*)
 * - lachesis site (public/*)
 * - lachesis app (tauri's app icon, which requires converting)
 */

import { execSync } from 'child_process'
import { cpSync, readFileSync, rmSync } from 'fs'
import { styleText } from 'util'

const skipGen = process.argv.includes('--skip-gen')

// Copy over to Atropos site
console.log(styleText('gray', 'Copying favicons... (atropos)'))
cpSync('packages/assets/favicon', 'apps/atropos/public', { recursive: true })
console.log(styleText('green', 'Copied favicons! (atropos)'))

// Copy over to Lachesis site
console.log(styleText('gray', 'Copying favicons... (lachesis)'))
cpSync('packages/assets/favicon', 'apps/lachesis/public', { recursive: true })
console.log(styleText('green', 'Copied favicons! (lachesis)'))

if (skipGen) {
  console.log(styleText('yellow', 'Skipping icon generation... (--skip-gen)'))
} else {
  console.log(styleText('gray', 'Generating icons... (lachesis/app)'))
  // Extract color from site.webmaniefest
  const THEME_COLOR = JSON.parse(
    readFileSync('packages/assets/favicon/site.webmanifest')
  ).theme_color
  // Generate tray-icon
  try {
    console.log(styleText('gray', 'checking for magick...'))
    execSync('which magick', { stdio: 'ignore' })
    console.log(styleText('italic', styleText('gray', 'found magick!')))
    // Generate source icon
    execSync(
      'magick -background none favicon.svg -resize 896x896 -gravity center -background none -extent 1024x1024 icon-source.png',
      { cwd: 'packages/assets/favicon' }
    )
    // Generate all tauri icons
    execSync(
      `pnpm tauri icon ../../packages/assets/favicon/icon-source.png --ios-color '${THEME_COLOR}'`,
      {
        cwd: 'apps/lachesis',
        stdio: 'pipe',
      }
    )
    rmSync('packages/assets/favicon/icon-source.png')
    // Generate tray icon
    execSync(
      'magick -background none packages/assets/favicon/favicon.svg -resize 48x48 -gravity center -background none -extent 64x64 apps/lachesis/src-tauri/icons/tray-icon.png'
    )
    console.log(styleText('gray', 'Generated tray-icon!'))
  } catch (err) {
    console.log(styleText('red', 'magick not found!'))
    process.exit(1)
  }
  // Generate tray-icon-template
  execSync('magick tray-icon.png -channel RGB -evaluate set 0 tray-icon-template.png', {
    cwd: 'apps/lachesis/src-tauri/icons',
  })
  console.log(styleText('gray', 'Generated tray-icon-template!'))
  console.log(styleText('green', 'Generated icons! (lachesis/app)'))
}
