/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Backgrounds: () => import('#controllers/backgrounds_controller'),
  FocusSessions: () => import('#controllers/focus_sessions_controller'),
  Goals: () => import('#controllers/goals_controller'),
  HabitPeriods: () => import('#controllers/habit_periods_controller'),
  Habits: () => import('#controllers/habits_controller'),
  Journals: () => import('#controllers/journals_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PasswordReset: () => import('#controllers/password_reset_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Scribbles: () => import('#controllers/scribbles_controller'),
  TaskDays: () => import('#controllers/task_days_controller'),
  Tasks: () => import('#controllers/tasks_controller'),
  VerifyEmail: () => import('#controllers/verify_email_controller'),
}
